server:
  port: 0

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:13001/ewm}
    username: ${SPRING_DATASOURCE_USERNAME:ewm_user}
    password: ${SPRING_DATASOURCE_PASSWORD:secret}
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: validate
