CREATE TABLE IF NOT EXISTS comments
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text      VARCHAR(500) NOT NULL,
    author_id BIGINT       NOT NULL,
    event_id  BIGINT       NOT NULL,
    created   TIMESTAMP    NOT NULL,
    edited    BOOLEAN      NOT NULL DEFAULT FALSE
);
