CREATE TABLE IF NOT EXISTS participation_request
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created      TIMESTAMP   NOT NULL,
    status       VARCHAR(20) NOT NULL,
    event_id     BIGINT      NOT NULL,
    requester_id BIGINT      NOT NULL
);
