spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:

        # COMMENT-SERVICE:
        - id: comment_service_public_event_comments
          uri: lb://comment-service
          predicates:
            - Path=/events/{eventId}/comments,/events/{eventId}/comments/**

        # EVENT-SERVICE:
        - id: event_service_public_events
          uri: lb://event-service
          predicates:
            - Path=/events,/events/**

        - id: event_service_public_categories
          uri: lb://event-service
          predicates:
            - Path=/categories,/categories/**

        - id: event_service_public_compilations
          uri: lb://event-service
          predicates:
            - Path=/compilations,/compilations/**

        # REQUEST-SERVICE:
        - id: request_service_private_event_requests
          uri: lb://request-service
          predicates:
            - Path=/users/{userId}/events/{eventId}/requests,/users/{userId}/events/{eventId}/requests/**

        # EVENT-SERVICE:
        - id: event_service_private_events
          uri: lb://event-service
          predicates:
            - Path=/users/{userId}/events,/users/{userId}/events/**

        # REQUEST-SERVICE:
        - id: request_service_private_user_requests
          uri: lb://request-service
          predicates:
            - Path=/users/{userId}/requests,/users/{userId}/requests/**

        # COMMENT-SERVICE:
        - id: comment_service_private
          uri: lb://comment-service
          predicates:
            - Path=/users/{userId}/comments,/users/{userId}/comments/**

        # EVENT-SERVICE:
        - id: event_service_admin_events
          uri: lb://event-service
          predicates:
            - Path=/admin/events,/admin/events/**

        - id: event_service_admin_categories
          uri: lb://event-service
          predicates:
            - Path=/admin/categories,/admin/categories/**

        - id: event_service_admin_compilations
          uri: lb://event-service
          predicates:
            - Path=/admin/compilations,/admin/compilations/**

        # COMMENT-SERVICE:
        - id: comment_service_admin
          uri: lb://comment-service
          predicates:
            - Path=/admin/comments,/admin/comments/**

        # USER-SERVICE:
        - id: user_service_admin
          uri: lb://user-service
          predicates:
            - Path=/admin/users,/admin/users/**

        # COMMENT-SERVICE:
        - id: comment_service_public_comments
          uri: lb://comment-service
          predicates:
            - Path=/comments,/comments/**

server:
  port: 8080

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - gateway
