server:
  port: 9090

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:13000/stats}
    username: ${SPRING_DATASOURCE_USERNAME:stats_user}
    password: ${SPRING_DATASOURCE_PASSWORD:secret}
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: validate
